version: '3'
services:
    mariadb:
        image: 'mariadb:10.3'
        volumes:
            - './docker/database:/var/lib/mysql'
        environment:
            - MYSQL_DATABASE=docker
            - MYSQL_USER=Hassan
            - MYSQL_PASSWORD=Ariz
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
    adminer:
        image: 'adminer:latest'
        ports:
            - '50000:8080'
    php:
        image: 'apache/php7.2'
        ports:
            - '30000:8081'
        volumes:
            - './:/usr/share/nginx/html'
        environment:
            - PHP_EXTENSIONS=pdo_mysql
        